version: "3.3"

services:
  mongo_db: 
    container_name: db_container
    image: mongo:latest
    restart: unless-stopped
    ports: 
      - 2717:27017
    volumes: 
      - mongo_db:/data/db 

  api:
    build: .
    image: sample-node-api
    container_name: sample-node-api
    restart: unless-stopped
    environment: 
      PORT: 3000
      MONGODB_URI: mongodb://mongo_db:27017
      DB_NAME: new_photos_share_container_docker
      NAME: new_test_db_docker_name
    depends_on:
      - mongo_db
    networks:
      - app-network

  proxy:
    image: nginx:alpine
    container_name: web-proxy
    restart: unless-stopped
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - api
    networks:
      - app-network

# still have data even shut down the container
volumes: 
  mongo_db: {}
  
networks:
  app-network:
    driver: bridge
